adminapp/urls.py
from django.urls import re_path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    re_path(r'^$', adminapp.categories, name='categories'),
    re_path(r'^categories/$', adminapp.categories, name='categories'),
    # re_path(r'^categories/create/$', adminapp.category_create, name='category_create'),

    re_path(r'^categories/create/$', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),

    # re_path(r'^category/update/(?P<pk>\d+)/$', adminapp.category_update, name='category_update'),

    re_path(r'^category/update/(?P<pk>\d+)/$', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),

    re_path(r'^category/delete/(?P<pk>\d+)/$', adminapp.category_del, name='category_del'),
    # re_path(r'^category/delete/(?P<pk>\d+)/$', adminapp.ProductCategoryDeleteView.as_view(), name='category_del'),
    re_path(r'^category/activate/(?P<pk>\d+)/$', adminapp.category_activate, name='category_activate'),

    re_path(r'^products/(?P<category_pk>\d+)/$', adminapp.products, name='products'),
    re_path(r'^product/create/(?P<category_pk>\d+)/$', adminapp.product_create, name='product_create'),
    # re_path(r'^product/read/(?P<product_pk>\d+)$', adminapp.product_read, name='product_read'),

    re_path(r'^product/read/(?P<pk>\d+)$', adminapp.ProductDetailView.as_view(), name='product_read'),

    re_path(r'^product/update/(?P<product_pk>\d+)/$', adminapp.product_update, name='product_update'),
    re_path(r'^product/delete/(?P<product_pk>\d+)/$', adminapp.product_del, name='product_del'),
    re_path(r'^product/activate/(?P<product_pk>\d+)/$', adminapp.product_activate, name='product_activate'),

    # re_path(r'^users/$', adminapp.users, name='users'),
    re_path(r'^users/$', adminapp.UserListView.as_view(), name='users'),
    re_path(r'^users/create/$', adminapp.user_create, name='user_create'),
    re_path(r'^users/update/(?P<pk>\d+)/$', adminapp.user_update, name='user_update'),
    re_path(r'^users/delete/(?P<pk>\d+)/$', adminapp.user_del, name='user_del'),
    re_path(r'^users/activate/(?P<pk>\d+)/$', adminapp.user_activate, name='user_activate'),
]

artlaser/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static

import mainapp.views as mainapp


urlpatterns = [
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^products/', include('mainapp.urls', namespace='products')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    # re_path(r'^products/', mainapp.products, name='products'),
    re_path(r'^contact/', mainapp.contact, name='contact'),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^administrator/', include('adminapp.urls', namespace='administrator')),

    re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/urls.py
from django.urls import re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^edit/$', authapp.edit, name='edit')
]

basketapp/urls.py
from django.urls import re_path
import basketapp.views as basketapp


app_name = 'basketapp'

urlpatterns = [
    re_path(r'^$', basketapp.main_basket, name='main_basket'),
    re_path(r'^product/add/(\d+)$', basketapp.product_add, name='product_add'),
    re_path(r'^product/del/(\d+)$', basketapp.product_del, name='product_del'),
    re_path(r'^product/edit/(?P<pk>\d+)/(?P<quantity>\d+)/$', basketapp.product_edit),
]

mainapp/urls.py
from django.contrib import admin
from django.urls import re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.products, name='index'),
    re_path(r'^category/(\d+)/$', mainapp.products, name='category'),
    re_path(r'^category/(\d+)/page/(\d+)/$', mainapp.products, name='page'),

    re_path(r'^product/(\d+)/$', mainapp.product, name='product'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Категория', max_length=64, unique=True)
    description = models.TextField(verbose_name='Описание категории', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name

    def upload_to_db(self, category):
        new_category = ProductCategory(name=category)
        try:
            new_category.save()
        except Exception as e:
            pass


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Название товара', max_length=128)
    vendor_id = models.CharField(verbose_name='Артикул', max_length=10, unique=True, blank=True)
    image = models.ImageField(upload_to='products_image', blank=True)
    short_descript = models.CharField(verbose_name='Краткое описание', max_length=64, blank=True)
    description = models.TextField(verbose_name='Описание товара', blank=True)
    price = models.DecimalField(verbose_name='Цена товара', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='Кол-во на складе', default=0)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        return '{} ({})'.format(self.name, self.category.name)

    def upload_to_db(self, product):
        row = product
        category = ProductCategory.objects.get(name=row[0])
        name = row[1]
        vendor_id = row[2]
        image = row[3]
        short_descript = row[4]
        description = row[5]
        price = row[6]
        quantity = row[7]
        prod = Product(category=category, name=name, vendor_id=vendor_id, image=image, short_descript=short_descript,
                       description=description, price=price, quantity=quantity)
        try:
            prod.save()
        except Exception as e:
            pass

mainapp/views.py
import json
import os
import random

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404

from mainapp.models import ProductCategory, Product
from basketapp.models import Basket


def get_categories():
    categories = []
    all_categories = {
        'pk': 0,
        'name': 'все'
    }

    categories.append(all_categories)
    categories.extend(ProductCategory.objects.filter(is_active=True))

    return categories

def main(request):
    title = 'Главная'
    categories = ProductCategory.objects.filter(is_active=True)
    products = Product.objects.filter(is_active=True, category__is_active=True)
    basket = Basket.get_basket(request)
    hot_product = get_hot_product()
    same_products = get_same_product(hot_product)
    context = {
        'title': title,
        'categories': categories,
        'products': products[1:5],
        'basket': basket,
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/index.html', context)


def products(request, pk=None, page=1):
    title = 'Каталог'
    products = []
    basket = Basket.get_basket(request)
    categories = get_categories()

    if pk:
        pk = int(pk)
        if pk == 0:
            products = Product.objects.filter(category__is_active=True, is_active=True)
        else:
            products = Product.objects.filter(category__pk=pk, is_active=True)

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'title': title,
            'categories': categories,
            'products': products_paginator,
            'basket': basket,
            'category_pk': pk,
        }
        return render(request, 'mainapp/products.html', context)

    hot_product = get_hot_product()
    same_products = get_same_product(hot_product)

    context = {
        'title': title,
        'categories': categories,
        'products': products,
        'basket': basket,
        'hot_product': hot_product,
        'same_products': same_products,
        'hot': True,
    }
    return render(request, 'mainapp/product_detail.html', context)


def product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    categories = get_categories()
    basket = Basket.get_basket(request)
    same_products = get_same_product(product)
    title = product.name

    context = {
        'title': title,
        'categories': categories,
        'hot_product': product,
        'basket': basket,
        'same_products': same_products,
        'hot': False,
    }

    return render(request, 'mainapp/product_detail.html', context)



def contact(request):
    """ Загрузка данных из json файла на диске """
    dirname = os.path.dirname(os.path.abspath(__file__))
    filename = os.path.join(dirname, 'contact_data.json')
    with open(filename, 'r', encoding='utf-8') as file:
        locations = json.load(file)

    title = 'Контакты'
    basket = Basket.get_basket(request)
    context = {
        'title': title,
        'locations': locations,
        'basket': basket,
    }
    return render(request, 'mainapp/contact.html', context)


def get_hot_product():
    products = Product.objects.filter(category__is_active=True)
    return random.sample(list(products), 1)[0]


def get_same_product(hot_product):
    same_products = Product.objects.filter(is_active=True, category=hot_product.category).exclude(pk=hot_product.pk)[:4]
    return same_products

mainapp/templates/mainapp/includes/inc__main_menu.html
{% load staticfiles %}

<header>
    <a class="logo" href="{% url 'main' %}"><img src="{% static '/img/my_store_logo.png' %}" alt="logo"></a>
    <a class="search" href="#"><img src="{% static '/img/search.png' %}" alt=""></a>
    <input class="search_input" type="search" placeholder="Поиск">
    <ul class="menu">
        <li>
            <a href="{% url 'main' %}"
               class="{% if request.resolver_match.url_name == 'main' %} click {% endif %}">
                ДОМОЙ
            </a>
        </li>
        <li>
            <a href="{% url 'products:index' %}"
               class="{% if request.resolver_match.namespaces.0 == 'products' %} click {% endif %}">
                КАТАЛОГ
            </a>
        </li>
        <li>
            <a href="{% url 'contact' %}"
               class="{% if request.resolver_match.url_name == 'contact' %} click {% endif %}">
                КОНТАКТЫ
            </a>
        </li>
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:edit' %}">{{user.username}}</a>
                {% if user.is_superuser %}
                <a href="{% url 'administrator:categories' %}">админка</a>{% endif %}
                <a href="{% url 'basket:main_basket' %}"
                    class="{% if request.resolver_match.namespaces.0 == 'basket' %} click {% endif %}">
                        {% if basket %}
                            <i class="fa fa-shopping-cart fa-lg" aria-hidden="true"></i>
                            ({{ basket.0.total_quantity }})
                        {% else %}
                            <i class="fa fa-shopping-cart fa-lg" aria-hidden="true"></i>
                        {% endif %}
                </a>
            {% endif %}
        </li>
        <li>
            {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">ВЫЙТИ <i class="fa fa-sign-out fa-lg" aria-hidden="true"></i></a>
            {% else %}
            <a href="{% url 'auth:login' %}"
               class="{% if request.resolver_match.url_name == 'login' %} click {% endif %}">
                ВОЙТИ
                <i class="fa fa-sign-in fa-lg" aria-hidden="true"></i>
            </a>
            {% endif %}
        </li>
    </ul>
</header>

mainapp/templates/mainapp/includes/inc__menu_content.html
<ul class="menu_products">
    {% for category in categories %}
        <li>
            <!-- подсветка категории при выборе горячего предложения -->
            {% if hot_product %}
            <a href="{% url 'products:category' category.pk %}"
            class="{% if hot_product.category.pk == category.pk %} active {% endif %}">
                {{ category.name.upper }}
            </a>
            {% elif products%}
            <!-- подсветка категории при выборе категории все -->
                {% if request.resolver_match.args.0 == '0' %}
                    <a href="{% url 'products:category' category.pk %}"
                    class="{% if request.resolver_match.args.0|add:0 == category.pk %} active {% endif %}">
                        {{ category.name.upper }}
                    </a>
                {% else %}
            <!-- подсветка категории при выборе товара -->
                    <a href="{% url 'products:category' category.pk %}"
                    class="{% if products.0.category.pk == category.pk %} active {% endif %}">
                        {{ category.name.upper }}
                    </a>
                {% endif %}
            {% endif %}
        </li>
    {% endfor %}
</ul>

mainapp/templates/mainapp/includes/inc__product_detail.html
{% load staticfiles %}


<div>
    <div class="prod_pic"><a href="/media/{{ hot_product.image }}" target="_blank">
        <img src="/media/{{ hot_product.image }}" alt=""></a>
    </div>
    <div class="control">
        <a href="#"><img src="/media/{{ hot_product.image }}" alt="1"></a>
        <a href="#"><img src="/media/{{ hot_product.image }}" alt="1"></a>
        <a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
    </div>
</div>
<div class="prod_text">
    <h3>{{ hot_product.name }}</h3>
    {% if hot %}
    <!--вывводим в случае горячего предложения иначе это выбраный товар-->
        <h4>Горячее предложение</h4>
    {% endif %}
    <p class="price">{{ hot_product.price }}<span>&#8372;</span></p>
    <a class="btn-order" href="{% url 'basket:product_add' hot_product.pk%}">Заказать
        <img src="{% static '/img/arrow_white.png' %}" alt="">
    </a>
    <div class="text">
        <p>{{ hot_product.short_descript }}</p>
    </div>
</div>