artlaser/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static

import mainapp.views as mainapp


urlpatterns = [
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^products/', include('mainapp.urls', namespace='products')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    # re_path(r'^products/', mainapp.products, name='products'),
    re_path(r'^contact/', mainapp.contact, name='contact'),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^administrator/', include('adminapp.urls', namespace='administrator')),

    re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/urls.py
from django.urls import re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^edit/$', authapp.edit, name='edit')
]

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст')
    phone = models.CharField(verbose_name='номер телефона', max_length=16, default='')

authapp/forms.py
import re
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from authapp.models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email', 'phone', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super(ShopUserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'phone':
                field.help_text = 'Формат номера +380881115522'
            else:
                field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError('Слишком молод еще!')
        return data

    def clean_phone(self):
        # Проверям номер телефона согласно стандарта E.164
        tmpl = re.compile(r'^\+{1}\d{10,14}\d$')
        data = self.cleaned_data['phone']
        result = re.match(tmpl, data)
        if not result:
            raise forms.ValidationError('Укажите номер в международном формате')
        else:
            return data


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'email', 'phone', 'age', 'avatar', 'password')
        
    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'phone':
                field.help_text = 'Формат номера +380881115522'
            else:
                field.help_text = ''
            # Скрываем текущий пароль
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError('Слишком молод еще!')
        return data

    def clean_phone(self):
        # Проверям номер телефона согласно стандарта E.164
        tmpl = r'^\+{1}\d{10,14}\d$'
        data = self.cleaned_data['phone']
        result = re.match(tmpl, data)
        if not result:
            raise forms.ValidationError('Укажите номер в международном формате')
        else:
            return data

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from django.urls import reverse

from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm


def login(request):
    title = 'Вход'
    form = ShopUserLoginForm()
    next = request.GET['next'] if 'next' in request.GET.keys() else ''
    # Проверяем, что данные пришли методом POST
    if request.method == 'POST':
        # Получаем данные и проверяем есть ли они в request
        form = ShopUserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(request, username=username, password=password)
            # Проверяем существует ли пользователь и то что он активен
            if user and user.is_active:
                # Авторизируем пользоваетля, помещаем его в request
                auth.login(request, user)
                if 'next' in request.POST.keys():
                    # Направляем пользователя на страницу с которой пришел
                    return HttpResponseRedirect(request.POST['next'])
                else:
                    return HttpResponseRedirect(reverse('main'))

    context = {
        'title': title,
        'login_form': form,
        'next': next,
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    # Разлогиниваем пользователя
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


def register(request):
    title = 'Регистрация'
    register_form = ShopUserRegisterForm()
    # Проверяем, что данные пришли методом POST
    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)
        # Получаем данные и проверяем есть ли они в request
        if register_form.is_valid():
            try:
                register_form.save()
                # После сохранения данных авторизируем пользователя и направляем на главную страницу
                user = auth.authenticate(request, username=request.POST['username'], password=request.POST['password1'])
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main'))
            except ValueError:
                pass

    context = {
        'title': title,
        'register_form': register_form,
    }
    return render(request, 'authapp/register.html', context)


def edit(request):
    title = 'Мой профиль'
    edit_form = ShopUserEditForm(instance=request.user)
    # Проверяем, что данные пришли методом POST
    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        # Получаем данные и проверяем есть ли они в request
        if edit_form.is_valid():
            # Сохраняем данные и остаемся в профиле
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))

    context = {
        'title': title,
        'edit_form': edit_form,
    }
    return render(request, 'authapp/edit.html', context)

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            АРТ-Лазер
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="{% static 'js/bootstrap.js' %}"></script>
    {% endblock %}
</head>
<body>
    <!--<div class="login">-->
    <!--<div class="h2 text-center head">-->
    <!--Вход в систему-->
    <!--</div>            -->
    <!---->
    {% block content %}

    {% endblock %}
    <!--</div>-->
</body>
</html>

authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ block.super }} - {{ title }}
{% endblock%}

{% block content %}
    <div class="register-form">
        <form action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
            <h2 class="text-center">Редактирование профиля</h2>
            {% csrf_token %}
            {{ edit_form.as_p }}
            <div class="user_avatar"><img src="/media/{{ user.avatar|default:'users_avatars/gravatar.png' }}"></div>
            <br>
            <input class="form-control btn btn-primary btn-block" type="submit" value="Cохранить">
        </form>
        <!--<button class="btn btn-round form-control last">-->
        <br>
           <p class="text-center"><a href="{% url 'main' %}" class="">назад</a></p>
        <!--</button>-->
    </div>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ block.super }} - {{ title }}
{% endblock%}

{% block content %}
    <div class="login-form">
        <form action="{% url 'auth:login' %}" method="post">
            <h2 class="text-center">Вход</h2>
            {% csrf_token %}
            {% if next %}
                <input type="hidden" name="next" value="{{ next }}">
            {% endif %}
            {{ login_form.as_p }}
            <br/>
            <!--<div class="form-group">-->
                <!--<input type="text" class="form-control" placeholder="имя пользователя" required="required">-->
            <!--</div>-->
            <!--<div class="form-group">-->
                <!--<input type="password" class="form-control" placeholder="пароль" required="required">-->
            <!--</div>-->
            <div class="form-group">
                <!--<button type="submit" class="btn btn-primary btn-block">Войти</button>-->
                <input class="form-control btn btn-primary btn-block" type="submit" value="войти">
            </div>
            <!--<input class="form-control" type="submit" value="войти">-->
            <div class="clearfix">
                <label class="pull-left checkbox-inline"><input type="checkbox"> Запомнить меня</label>
                <a href="#" class="pull-right">Забыли пароль?</a>
            </div>
        </form>
        <!--<button class="btn btn-round form-control">-->
            <p class="text-center"><a href="{% url 'auth:register' %}" class="">Регистрация</a></p>
            <p class="text-center"><a href="{% url 'main' %}" class="">< назад</a></p>
        <!--</button>-->
    </div>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ block.super }} - {{ title }}
{% endblock%}

{% block content %}
    <div class="register-form">
        <form action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
            <h2 class="text-center">Регистрация</h2>
            {% csrf_token %}
            {{ register_form.as_p }}
            <br>
            <input class="form-control btn btn-primary btn-block" type="submit" value="Зарегистрироваться">
            <br>
            <p class="text-center"><a href="{% url 'main' %}" class="">назад</a></p>
        </form>
    </div>
{% endblock %}