adminapp/urls.py
from django.urls import re_path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    re_path(r'^$', adminapp.categories, name='categories'),
    re_path(r'^categories/$', adminapp.categories, name='categories'),
    # re_path(r'^categories/create/$', adminapp.category_create, name='category_create'),

    re_path(r'^categories/create/$', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),

    # re_path(r'^category/update/(?P<pk>\d+)/$', adminapp.category_update, name='category_update'),

    re_path(r'^category/update/(?P<pk>\d+)/$', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),

    re_path(r'^category/delete/(?P<pk>\d+)/$', adminapp.category_del, name='category_del'),
    # re_path(r'^category/delete/(?P<pk>\d+)/$', adminapp.ProductCategoryDeleteView.as_view(), name='category_del'),
    re_path(r'^category/activate/(?P<pk>\d+)/$', adminapp.category_activate, name='category_activate'),

    re_path(r'^products/(?P<category_pk>\d+)/$', adminapp.products, name='products'),
    re_path(r'^product/create/(?P<category_pk>\d+)/$', adminapp.product_create, name='product_create'),
    # re_path(r'^product/read/(?P<product_pk>\d+)$', adminapp.product_read, name='product_read'),

    re_path(r'^product/read/(?P<pk>\d+)$', adminapp.ProductDetailView.as_view(), name='product_read'),

    re_path(r'^product/update/(?P<product_pk>\d+)/$', adminapp.product_update, name='product_update'),
    re_path(r'^product/delete/(?P<product_pk>\d+)/$', adminapp.product_del, name='product_del'),
    re_path(r'^product/activate/(?P<product_pk>\d+)/$', adminapp.product_activate, name='product_activate'),

    # re_path(r'^users/$', adminapp.users, name='users'),
    re_path(r'^users/$', adminapp.UserListView.as_view(), name='users'),
    re_path(r'^users/create/$', adminapp.user_create, name='user_create'),
    re_path(r'^users/update/(?P<pk>\d+)/$', adminapp.user_update, name='user_update'),
    re_path(r'^users/delete/(?P<pk>\d+)/$', adminapp.user_del, name='user_del'),
    re_path(r'^users/activate/(?P<pk>\d+)/$', adminapp.user_activate, name='user_activate'),
]

artlaser/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static

import mainapp.views as mainapp


urlpatterns = [
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^products/', include('mainapp.urls', namespace='products')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    # re_path(r'^products/', mainapp.products, name='products'),
    re_path(r'^contact/', mainapp.contact, name='contact'),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^administrator/', include('adminapp.urls', namespace='administrator')),

    re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/urls.py
from django.urls import re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^edit/$', authapp.edit, name='edit')
]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
import re
from django import forms
from mainapp.models import ProductCategory, Product
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = ('is_active', 'username', 'first_name', 'last_name', 'email', 'phone', 'age', 'avatar', 'password')


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import user_passes_test
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.utils.decorators import method_decorator

from adminapp.forms import ShopUserAdminEditForm, ProductCategoryEditForm, ProductEditForm
from authapp.models import ShopUser
from authapp.forms import ShopUserRegisterForm
from mainapp.models import ProductCategory, Product


@user_passes_test(lambda user: user.is_superuser)
def categories(request):
    title = 'Категории'

    categories_list = ProductCategory.objects.all().order_by('-is_active', 'name')

    context = {
        'title': title,
        'objects': categories_list,
    }

    return render(request, 'adminapp/categories.html', context)


# @user_passes_test(lambda user: user.is_superuser)
# def category_create(request):
#     title = 'Новая категория'
#     form = ProductCategoryEditForm()
#     if request.method == 'POST':
#         form = ProductCategoryEditForm(request.POST)
#         # Получаем данные и проверяем есть ли они в request
#         if form.is_valid():
#             try:
#                 form.save()
#                 # После сохранения данных возвращаемся к списку пользователей
#                 return HttpResponseRedirect(reverse('administrator:categories'))
#             except ValueError:
#                 pass
#
#     context = {
#         'title': title,
#         'form': form,
#     }
#     return render(request, 'adminapp/category_edit.html', context)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_edit.html'
    success_url = reverse_lazy('administrator:categories')
    # fields = ('__all__')
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda user: user.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# @user_passes_test(lambda user: user.is_superuser)
# def category_update(request, pk):
#     title = 'Редактирование категории'
#
#     category = get_object_or_404(ProductCategory, pk=int(pk))
#     form = ProductCategoryEditForm(instance=category)
#     if request.method == 'POST':
#         form = ProductCategoryEditForm(request.POST, instance=category)
#         # Получаем данные и проверяем есть ли они в request
#         if form.is_valid():
#             try:
#                 form.save()
#                 # После сохранения данных возвращаемся к списку пользователей
#                 return HttpResponseRedirect(reverse('administrator:categories'))
#             except ValueError:
#                 pass
#         else:
#             form = ProductCategoryEditForm(instance=object)
#
#     context = {
#         'title': title,
#         'form': form,
#     }
#     return render(request, 'adminapp/category_edit.html', context)


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_edit.html'
    success_url = reverse_lazy('administrator:categories')
    form_class = ProductCategoryEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование категории'
        return context

    @method_decorator(user_passes_test(lambda user: user.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


@user_passes_test(lambda user: user.is_superuser)
def category_del(request, pk):
    category = get_object_or_404(ProductCategory, pk=int(pk))
    if category:
        category.is_active = False
        category.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


# class ProductCategoryDeleteView(DeleteView):
#     model = ProductCategory
#     template_name = # нужен отдельно шаблон
#     success_url = reverse_lazy('administrator:categories')
#
#     def delete(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         self.object.is_active = False
#         self.object.save()
#         return HttpResponseRedirect(self.success_url())


@user_passes_test(lambda user: user.is_superuser)
def category_activate(request, pk):
    category = get_object_or_404(ProductCategory, pk=int(pk))
    if category:
        category.is_active = True
        category.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


# @user_passes_test(lambda user: user.is_superuser)
# def users(request):
#     title = 'Пользователи'
#     users_list = ShopUser.objects.all().order_by('-is_active', 'username')
#
#     context = {
#         'title': title,
#         'objects': users_list,
#     }
#
#     return render(request, 'adminapp/users.html', context)


class UserListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Пользователи'
        return context

    @method_decorator(user_passes_test(lambda user: user.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


@user_passes_test(lambda user: user.is_superuser)
def user_create(request):
    title = 'Регистрация пользователя'
    form = ShopUserRegisterForm()
    if request.method == 'POST':
        form = ShopUserRegisterForm(request.POST, request.FILES)
        # Получаем данные и проверяем есть ли они в request
        if form.is_valid():
            try:
                form.save()
                # После сохранения данных возвращаемся к списку пользователей
                return HttpResponseRedirect(reverse('administrator:users'))
            except ValueError:
                pass

    context = {
        'title': title,
        'form': form,
    }
    return render(request, 'adminapp/user_edit.html', context)


@user_passes_test(lambda user: user.is_superuser)
def user_update(request, pk):
    title = 'Редактирование профиля'
    user = get_object_or_404(ShopUser, pk=int(pk))
    if user:
        if request.method == 'POST':
            form = ShopUserAdminEditForm(request.POST, request.FILES, instance=user)
            # Получаем данные и проверяем есть ли они в request
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('administrator:users'))
        else:
            form = ShopUserAdminEditForm(instance=user)

        context = {
            'title': title,
            'form': form,
            'object': user,
        }
        return render(request, 'adminapp/user_edit.html', context)


@user_passes_test(lambda user: user.is_superuser)
def user_del(request, pk):
    user = get_object_or_404(ShopUser, pk=int(pk))
    if user:
        # user.delete()
        user.is_active = False
        user.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@user_passes_test(lambda user: user.is_superuser)
def user_activate(request, pk):
    user = get_object_or_404(ShopUser, pk=int(pk))
    if user:
        # user.delete()
        user.is_active = True
        user.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@user_passes_test(lambda user: user.is_superuser)
def products(request, category_pk):
    title = 'Товары'

    products_list = Product.objects.filter(category__pk=category_pk).order_by('name')
    # Получим текущую категорию и передадим в шаблон, чтобы не было ошибки, если категория пустая
    category = get_object_or_404(ProductCategory, pk=int(category_pk))

    context = {
        'title': title,
        'objects': products_list,
        'category': category,
    }

    return render(request, 'adminapp/products_list.html', context)


# @user_passes_test(lambda user: user.is_superuser)
# def product_read(request, product_pk):
#     product = get_object_or_404(Product, pk=int(product_pk))
#     title = 'Подробнее'
#     context = {
#         'title': title,
#         'object': product,
#     }
#     return render(request, 'adminapp/product_detail.html', context)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_detail.html'

    @method_decorator(user_passes_test(lambda user: user.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


@user_passes_test(lambda user: user.is_superuser)
def product_create(request, category_pk):
    title = 'Добавить товар'
    category = get_object_or_404(ProductCategory, pk=int(category_pk))
    if request.method == 'POST':
        form = ProductEditForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('administrator:products', kwargs={'category_pk': category_pk}))
    else:
        form = ProductEditForm(initial={'category': category})

    context = {
        'title': title,
        'category': category,
        'form': form,
    }

    return render(request, 'adminapp/product_edit.html', context)


@user_passes_test(lambda user: user.is_superuser)
def product_update(request, product_pk):
    title = 'Изменить товар'
    product = get_object_or_404(Product, pk=int(product_pk))
    category = product.category
    if request.method == 'POST':
        form = ProductEditForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('administrator:products', kwargs={'category_pk': category.pk}))
    else:
        form = ProductEditForm(instance=product)

    context = {
        'title': title,
        'category': category,
        'form': form,
    }

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>
    {% block title %}
        Админка
    {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static '/css/normalize.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
        <link rel="stylesheet" href="{% static '/fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/basket_scripts.js' %}"></script>
    {% endblock %}
</head>
<body>

        {% block container %}
        {% endblock %}

</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block title %}
{{ block.super }} - {{ title }}
{% endblock %}

{% block container %}
<!--<div class="container clr">-->
<div class="container clearfix">
    <div class="hero-back">
        <!-- ====== MENU ====== -->
        {% include 'adminapp/includes/inc__menu.html' %}
        <!-- ====== MENU END ====== -->
        <div class="h2">{{ title }}</div>
    </div>

    <!-- ====== CONTENT ====== -->
    <div class="content">
        <table>
            <thead>
            <tr>
                <th scope="col">Категория</th>
                <th scope="col">Описание</th>
                <th scope="col">Активна</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% for object in objects %}
            <tr>
                <th scope="row" ><a href="{% url 'administrator:products' object.pk %}">{{ object.name }}</a></th>
                <td>{{ object.description }}</td>
                <td class="td-total">
                    {% if object.is_active %}
                    <i class="fa fa-check fa-2x" aria-hidden="true"></i>
                    {% else %}
                    <i class="fa fa-times fa-2x" aria-hidden="true"></i>
                    {% endif %}
                </td>
                <td class="td-total">
                    <a href="{% url 'administrator:category_update' object.pk %}">
                        <button class="btn-cat">
                            Изменить
                        </button>
                    </a>
                    {% if object.is_active %}
                    <a href="{% url 'administrator:category_del' object.pk %}">
                        <button class="btn-cat">
                            Отключить
                        </button>
                    </a>
                    {% else %}
                    <a href="{% url 'administrator:category_activate' object.pk %}">
                        <button class="btn-cat">
                            Включить
                        </button>
                    </a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
            </tbody>
            <tr>
                <td colspan="4" class="td-total">
                    <a href="{% url 'administrator:category_create' %}">
                        <button class="btn-cat">
                            Добавить котегорию
                        </button>
                    </a>
                 </td>
            </tr>
            <tfoot>
            </tfoot>
        </table>
    </div>    <!-- ====== CONTENT END ====== -->
</div>
<!--</div>  ====== CONTAINER END ====== -->
{% endblock %}

adminapp/templates/adminapp/category_edit.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ block.super }} - {{ title }}
{% endblock%}

{% block content %}
    <div class="register-form">
        <form method="post" enctype="multipart/form-data">
            <h2 class="text-center">{{ title }}</h2>
            {% csrf_token %}
            {{ form.as_p}}
            <br>
            <input class="form-control btn btn-primary btn-block" type="submit" value="Cохранить">
        </form>
        <!--<button class="btn btn-round form-control last">-->
        <br>
           <p class="text-center"><a href="{% url 'administrator:categories' %}" class="">назад</a></p>
        <!--</button>-->
    </div>
{% endblock %}

adminapp/templates/adminapp/product_detail.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% load tags %}

{% block title %}
{{ block.super }} - {{ title }}
{% endblock %}

{% block container %}
<!--<div class="container clr">-->
<div class="container clearfix">
    <div class="hero-back">
        <!-- ====== MENU ====== -->
        {% include 'adminapp/includes/inc__menu.html' %}
        <!-- ====== MENU END ====== -->
        <div class="h3">{{ object.name }}</div>
    </div>

    <!-- ====== CONTENT ====== -->
    <div class="content">
        <div class="product">
            <div>
                <div class="prod_pic"><a href="{{ object.image|default_image }}" target="_blank">
                    <img src="{{ object.image|default_image }}" alt=""></a>
                </div>
            </div>
            <div class="prod_text">
                <h3>{{ object.name }}</h3>
                <p align="center">Артикул: <h4>{{ object.vendor_id }}</h4></p>
                <p class="price">{{ object.price }}<span>&#8372;</span></p>
                <div class="text">
                    <p><u>Категория:</u> <br> {{ object.category.name }} </p>
                    <br>
                    <p><u>Краткое описание:</u> <br> {{ object.short_descript }}</p>
                    <br>
                    <p><u>Описание:</u> <br> {{ object.description }}</p>
                    <br>
                </div>
                <hr>
                <a href="{% url 'administrator:products' object.category.pk %}">
                    <button class="btn-cat"><< Назад</button>
                </a>
            </div>
        </div>
    </div>    <!-- ====== CONTENT END ====== -->
</div>
<!--</div>  ====== CONTAINER END ====== -->
{% endblock %}

adminapp/templates/adminapp/product_edit.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ block.super }} - {{ title }}
{% endblock%}

{% block content %}
    <div class="register-form">
        <form method="post" enctype="multipart/form-data">
            <h2 class="text-center">{{ title }}</h2>
            {% csrf_token %}
            {{ form.as_p}}
            <br>
            <input class="form-control btn btn-primary btn-block" type="submit" value="Cохранить">
        </form>
        <!--<button class="btn btn-round form-control last">-->
        <br>
           <p class="text-center"><a href="{% url 'administrator:products' category.pk %}" class="">назад</a></p>
        <!--</button>-->
    </div>
{% endblock %}

adminapp/templates/adminapp/products_list.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% load tags %}

{% block title %}
{{ block.super }} - {{ title }}
{% endblock %}

{% block container %}
<!--<div class="container clr">-->
<div class="container clearfix">
    <div class="hero-back">
        <!-- ====== MENU ====== -->
        {% include 'adminapp/includes/inc__menu.html' %}
        <!-- ====== MENU END ====== -->
        <div class="h2">{{ title }}</div>
    </div>

    <!-- ====== CONTENT ====== -->
    <div class="content">
        <table>
            <thead>
            <tr>
                <th colspan="5" scope="col">Категория "{{ objects.0.category.name }}"</th>
            </tr>
            <tr>
                <th scope="col">Товар</th>
                <th scope="col">Краткое описание</th>
                <th scope="col">Изображение</th>
                <th scope="col">Цена</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% for object in objects %}
            <tr style="{% if not object.is_active%}opacity:0.3{% endif %}">
                <th scope="row">
                    <a href="{% url 'administrator:product_read' object.pk %}">{{ object.name }}</a>
                </th>
                <td>{{ object.short_descript }}</td>
                <td class="td-image">
                    <img class="img_min" src="{{ object.image|default_image }}" alt="">
                </td>
                <td class="td-price">{{ object.price }}</td>
                <td class="td-total">
                    <a href="{% url 'administrator:product_update' object.pk %}">
                        <button class="btn-cat">
                            Изменить
                        </button>
                    </a>
                    {% if object.is_active %}
                    <a href="{% url 'administrator:product_del' object.pk %}">
                        <button class="btn-cat">
                            Отключить
                        </button>
                    </a>
                    {% else %}
                    <a href="{% url 'administrator:product_activate' object.pk %}">
                        <button class="btn-cat">
                            Включить
                        </button>
                    </a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
            </tbody>
            <tr>
                <td colspan="5" class="td-total">
                    <a href="{% url 'administrator:product_create' category.pk %}">
                        <button class="btn-cat">
                            Добавить товар
                        </button>
                    </a>
                    <a href="{% url 'administrator:categories' %}">
                        <button class="btn-cat">
                            Назад
                        </button>
                    </a>
                </td>
            </tr>
            <tfoot>
            </tfoot>
        </table>
    </div>    <!-- ====== CONTENT END ====== -->
</div>
<!--</div>  ====== CONTAINER END ====== -->
{% endblock %}

adminapp/templates/adminapp/user_edit.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}
{% load tags %}

{% block title %}
    {{ block.super }} - {{ title }}
{% endblock%}

{% block content %}
    <div class="register-form">
        <form method="post" enctype="multipart/form-data">
            <h2 class="text-center">{{ title }}</h2>
            {% csrf_token %}
            {{ form.as_p}}
            <div class="user_avatar"><img src="{{ object.avatar|default_avatar }}"></div>
            <br>
            <input class="form-control btn btn-primary btn-block" type="submit" value="Cохранить">
        </form>
        <br>
           <p class="text-center"><a href="{% url 'administrator:users' %}" class="">назад</a></p>
    </div>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% load tags %}

{% block title %}
{{ block.super }} - {{ title }}
{% endblock %}

{% block container %}
<!--<div class="container clr">-->
<div class="container clearfix">
    <div class="hero-back">
        <!-- ====== MENU ====== -->
        {% include 'adminapp/includes/inc__menu.html' %}
        <!-- ====== MENU END ====== -->
        <div class="h2">{{ title }}</div>
    </div>

    <!-- ====== CONTENT ====== -->
    <div class="content">
        <table>
            <thead>
            <tr>
                <th scope="col">Данные о пользователе</th>
                <th scope="col">Контактные данные</th>
                <th scope="col">Аватар</th>
                <th scope="col">Активен</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
            <tr>
                <td>
                    <p class="{% if object.is_superuser %}u-red{% else %}u-green{% endif %}">
                        {% if object.is_superuser %}
                        администратор
                        {% else %}
                        пользователь
                        {% endif %}</p>
                    <p>Логин: <span>{{ object.username }}</span></p>
                    <p>Имя: <span>{{ object.first_name }}</span></p>
                    <p>Фамилия: <span>{{ object.last_name }}</span></p>
                    <p>Последний вход: <span>{{ object.last_login }}</span></p>
                </td>
                <td>
                    <p>e-mail: <span>{{ object.email }}</span></p>
                    <p>тел.: <span>{{ object.phone }}</span></p>
                </td>
                <td class="td-image">
                    <img class="img_min" src="{{ object.avatar|default_avatar }}" alt="">
                </td>
                <td class="td-total">
                    {% if object.is_active %}
                        <i class="fa fa-check fa-2x" aria-hidden="true"></i>
                    {% else %}
                        <i class="fa fa-times fa-2x" aria-hidden="true"></i>
                    {% endif %}
                </td>
                <td class="td-total">
                    <a href="{% url 'administrator:user_update' object.pk %}">
                        <button class="btn-cat">
                            Изменить
                        </button>
                    </a>
                    {% if object.username != 'django' %}
                    {% if object.is_active %}
                        <a href="{% url 'administrator:user_del' object.pk %}">
                            <button class="btn-cat">
                                Отключить
                            </button>
                        </a>
                        {% else %}
                        <a href="{% url 'administrator:user_activate' object.pk %}">
                            <button class="btn-cat">
                                Включить
                            </button>
                        </a>
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
            </tbody>
            <tr>
                <td colspan="5" class="td-total">
                    <a href="{% url 'administrator:user_create' %}">
                        <button class="btn-cat">Добавить пользователя</button>
                    </a>
                </td>
            </tr>
            <tfoot>
            </tfoot>
        </table>
    </div>    <!-- ====== CONTENT END ====== -->
</div>
<!--</div>  ====== CONTAINER END ====== -->
{% endblock %}