artlaser/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static

import mainapp.views as mainapp


urlpatterns = [
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^products/', include('mainapp.urls', namespace='products')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    # re_path(r'^products/', mainapp.products, name='products'),
    re_path(r'^contact/', mainapp.contact, name='contact'),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^administrator/', include('adminapp.urls', namespace='administrator')),

    re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/urls.py
from django.urls import re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^edit/$', authapp.edit, name='edit')
]

mainapp/urls.py
from django.contrib import admin
from django.urls import re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.products, name='index'),
    re_path(r'^category/(\d+)/$', mainapp.products, name='category'),
    re_path(r'^category/(\d+)/page/(\d+)/$', mainapp.products, name='page'),

    re_path(r'^product/(\d+)/$', mainapp.product, name='product'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Категория', max_length=64, unique=True)
    description = models.TextField(verbose_name='Описание категории', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name

    def upload_to_db(self, category):
        new_category = ProductCategory(name=category)
        try:
            new_category.save()
        except Exception as e:
            pass


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Название товара', max_length=128)
    vendor_id = models.CharField(verbose_name='Артикул', max_length=10, unique=True, blank=True)
    image = models.ImageField(upload_to='products_image', blank=True)
    short_descript = models.CharField(verbose_name='Краткое описание', max_length=64, blank=True)
    description = models.TextField(verbose_name='Описание товара', blank=True)
    price = models.DecimalField(verbose_name='Цена товара', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='Кол-во на складе', default=0)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        return '{} ({})'.format(self.name, self.category.name)

    def upload_to_db(self, product):
        row = product
        category = ProductCategory.objects.get(name=row[0])
        name = row[1]
        vendor_id = row[2]
        image = row[3]
        short_descript = row[4]
        description = row[5]
        price = row[6]
        quantity = row[7]
        prod = Product(category=category, name=name, vendor_id=vendor_id, image=image, short_descript=short_descript,
                       description=description, price=price, quantity=quantity)
        try:
            prod.save()
        except Exception as e:
            pass

mainapp/views.py
import json
import os
import random

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404

from mainapp.models import ProductCategory, Product
from basketapp.models import Basket


def get_categories():
    categories = []
    all_categories = {
        'pk': 0,
        'name': 'все'
    }

    categories.append(all_categories)
    categories.extend(ProductCategory.objects.filter(is_active=True))

    return categories

def main(request):
    title = 'Главная'
    categories = ProductCategory.objects.filter(is_active=True)
    products = Product.objects.filter(is_active=True, category__is_active=True)
    basket = Basket.get_basket(request)
    hot_product = get_hot_product()
    same_products = get_same_product(hot_product)
    context = {
        'title': title,
        'categories': categories,
        'products': products[1:5],
        'basket': basket,
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/index.html', context)


def products(request, pk=None, page=1):
    title = 'Каталог'
    products = []
    basket = Basket.get_basket(request)
    categories = get_categories()

    if pk:
        pk = int(pk)
        if pk == 0:
            products = Product.objects.filter(category__is_active=True, is_active=True)
        else:
            products = Product.objects.filter(category__pk=pk, is_active=True)

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'title': title,
            'categories': categories,
            'products': products_paginator,
            'basket': basket,
            'category_pk': pk,
        }
        return render(request, 'mainapp/products.html', context)

    hot_product = get_hot_product()
    same_products = get_same_product(hot_product)

    context = {
        'title': title,
        'categories': categories,
        'products': products,
        'basket': basket,
        'hot_product': hot_product,
        'same_products': same_products,
        'hot': True,
    }
    return render(request, 'mainapp/product_detail.html', context)


def product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    categories = get_categories()
    basket = Basket.get_basket(request)
    same_products = get_same_product(product)
    title = product.name

    context = {
        'title': title,
        'categories': categories,
        'hot_product': product,
        'basket': basket,
        'same_products': same_products,
        'hot': False,
    }

    return render(request, 'mainapp/product_detail.html', context)



def contact(request):
    """ Загрузка данных из json файла на диске """
    dirname = os.path.dirname(os.path.abspath(__file__))
    filename = os.path.join(dirname, 'contact_data.json')
    with open(filename, 'r', encoding='utf-8') as file:
        locations = json.load(file)

    title = 'Контакты'
    basket = Basket.get_basket(request)
    context = {
        'title': title,
        'locations': locations,
        'basket': basket,
    }
    return render(request, 'mainapp/contact.html', context)


def get_hot_product():
    products = Product.objects.filter(category__is_active=True)
    return random.sample(list(products), 1)[0]


def get_same_product(hot_product):
    same_products = Product.objects.filter(is_active=True, category=hot_product.category).exclude(pk=hot_product.pk)[:4]
    return same_products

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>
    {% block title %}
        АРТ-Лазер
    {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static '/css/normalize.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
        <link rel="stylesheet" href="{% static '/fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/basket_scripts.js' %}"></script>
    {% endblock %}
</head>
<body>
    <div class="container clr">
        {% block container %}
        {% endblock %}
    </div> <!-- ====== CONTAINER END ====== -->
    {% block footer %}
        <footer>
        <div class="info">
            <div class="contact_us">
                <a href="contact.html"><h4>Наши контакты</h4></a>
                <p>г. Луцк, Волынская обл., Украина</p>
                <p>+380 (96) 890-77-11 <br/>
                <a href="mailto:office&@art-laser.com.ua">office&#64;art-laser.com.ua</a></p>
            </div>
            <div class="useful">
                <h4>Полезная информация</h4>
                <div>
                    <a href="">Условия продажи</a>
                    <a href="">Оплата</a>
                    <a href="">Доставка</a>
                </div>
                <div>
                    <a href="">История продаж</a>
                    <a href="">Карьера</a>
                    <a href="">Обмены &amp; возвраты</a>
                </div>
            </div>
            <div class="subscribe">
                <h4>Оставайтесь на связи!</h4>
                <p>Подпишитесь, чтобы узнать о наших последних новостях, продуктах и специальных предложениях только для подписчиков</p>
                <form class="email" action="" method="post">
                    <input type="email" placeholder="укажите ваш email">
                    <div class="but">
                        <img src="{% static '/img/send.png' %}" alt="">
                    </div>
                </form>
            </div>
        </div>
        <div class="copyright">
            <p>&copy; ART-Laser {% now "Y" %}. Все права защищены</p>
            <div class="icon_soc">
                <a href="https://www.facebook.com/" target="_blank"><img src="{% static '/img/facebook.png' %}" alt=""></a>
                <a href="https://twitter.com/" target="_blank"><img src="{% static '/img/twitter.png' %}" alt=""></a>
                <a href="https://plus.google.com/" target="_blank"><img src="{% static '/img/google.png' %}" alt=""></a>
                <a href="https://www.pinterest.com/" target="_blank"><img src="{% static '/img/pinterest.png' %}" alt=""></a>
            </div>
            <p>Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
        </div>
    </footer> <!-- ====== FOTER END ====== -->
    {% endblock %}
</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ block.super }} - {{ title }}
{% endblock%}

{% block container %}
    <div class="container clearfix">
        <div class="hero-back">
            {% include 'mainapp/includes/inc__main_menu.html' %}
            <div class="h2">Наши контакты</div>
        </div>
        <!-- ====== CONTENT ====== --> 
        <div class="content">
            <div class="maps">
                {% for location in locations%}
                <a class="frame">
                   <iframe src="{{ location.map }}" width="370" height="370" frameborder="0" style="border:0" allowfullscreen></iframe>
                    <div class="address">
                      <img src="{% static '/img/geo.png' %}" alt="">
                          <h3>{{ location.country }}</h3>
                            <p><b>Тел:</b> <br> <strong>{{ location.phone }}</strong></p>
                            <p><b>Email:</b> <br> <strong>{{ location.email }}</strong></p>
                            <p><b>Адрес:</b> <br>{{ location.address }}</p>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>    <!-- ====== CONTENT END ====== -->
    </div>     <!-- ====== CONTAINER END ====== -->
{% endblock%}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load tags %}

{% block title %}
    {{ block.super }} - {{ title }}
{% endblock%}

{% block container %}
    <div class="slider trending">
        {% include 'mainapp/includes/inc__main_menu.html' %}
        <div class="block_text">
            <h3><span style="color: #43a047;">ТЕНДЕНЦИИ</span></h3>
            <h2>Конструкторы</h2>
            <p>Уникальные товары оптом и на заказ</p>
            <a class="button_order" href="#">Заказать<img src="{% static '/img/arrow.png' %}" alt=""></a>
        </div>
        <nav>
            <a class="circle" href="#"></a>
            <a class="circle circle_active" href="#"></a>
            <a class="circle" href="#"></a>
        </nav>
    </div>
    <div class="content clearfix">
        <div class="product_header">
            <ul class="menu_content">
                <li><a class="click" href="#">Популярные</a></li>
                <li><a href="#">Новинки</a></li>
            </ul>
            <a class="explore" href="{% url 'products:index' %}">показать все<img src="{% static '/img/arrow.png' %}" alt=""></a>
        </div>
        <div class="preview">
            {% for product in products %}
            <a class="block_pic" href="{% url 'products:product' product.pk %}">
                <img src="{{ product.image|default_image }}" alt="prod">
                <div class="txt">
                    <div class="b_c"><img src="{% static '/img/arrow.png' %}" alt="arrow"></div>
                    <h3>{{product.category.name}}</h3>
                    <p>{{product.short_descript}}</p>
                </div>
            </a>
            {% endfor %}
            <!-- <a class="block_pic" href="#"><img src="{% static '/img/product_owl.jpg' %}" alt="prod">
                <div class="txt">
                    <div class="b_c"><img src="{% static '/img/arrow.png' %}" alt="arrow"></div>
                    <h3>Светильник</h3>
                    <p>Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated
                        black or highly polished chrome.</p>
                </div>
            </a>
            <a class="block_pic" href="#"><img src="{% static '/img/product_plane.jpg' %}" alt="prod">
                <div class="txt">
                    <div class="b_c"><img src="{% static '/img/arrow.png' %}" alt="arrow"></div>
                    <h3>Конструктор</h3>
                    <p>Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated
                        black or highly polished chrome.</p>
                </div>
            </a>
            <a class="block_pic" href="#"><img src="{% static '/img/product_house.jpg' %}" alt="prod">
                <div class="txt">
                    <div class="b_c"><img src="{% static '/img/arrow.png' %}" alt="arrow"></div>
                    <h3>Светильник</h3>
                    <p>Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated
                        black or highly polished chrome.</p>
                </div>
            </a> -->
        </div>
        <div class="exclusive">
            <div class="exclusive_left">
                <div class="block_text_exclusive">
                    <h3>эксклюзив</h3>
                    <h2>Коробка</h2>
                    <p>Коллекционная коробка. Тонировка и гравировка.</p>
                    <a class="button_order" href="#">Заказать<img src="{% static '/img/arrow.png' %}" alt=""></a>
                </div>
            </div>
            <div class="exclusive_right">
                <div class="block_text_exclusive">
                    <h3>эксклюзив</h3>
                    <h2>Светильник</h2>
                    <p>Уникальная форма. Новинка на рынке.</p>
                    <a class="button_order" href="#">Заказать<img src="{% static '/img/arrow.png' %}" alt=""></a>
                </div>
            </div>
        </div>
        <div class="product_header">
            <h2>Популярные товары</h2>
            <a class="explore" href="#">показать все<img src="{% static '/img/arrow.png' %}" alt=""></a>
        </div>
        <div class="pic">
            {% for product in products %}
                <a href="{% url 'products:product' product.pk %}"><img src="{{ product.image|default_image }}" alt=""></a>
            <!-- <a href="#"><img src="{% static '/img/product_truck.jpg' %}" alt=""></a>
            <a href="product_detail.html"><img src="{% static '/img/product_heli.jpg' %}" alt=""></a>
            <a href="#"><img src="{% static '/img/product_owl.jpg' %}" alt=""></a>
            <a href="#"><img src="{% static '/img/product_cone.jpg' %}" alt=""></a>
            <a href="#"><img src="{% static '/img/product_house.jpg' %}" alt=""></a>
            <a href="#"><img src="{% static '/img/product_plane.jpg' %}" alt=""></a> -->
            {% endfor %}
        </div>
        <div class="slider hot_deal">
            <div class="block_text">
                <h3>ГОРЯЧЕЕ ПРЕДЛОЖЕНИЕ</h3>
                <h2>Ночники</h2>
                <p>Экологически чистые материалы. С регулирвкой освещенности.</p>
                <a class="button_order" href="#">Заказать<img src="{% static '/img/arrow.png' %}" alt=""></a>
            </div>
            <nav>
                <a class="circle" href="#"></a>
                <a class="circle circle_active" href="#"></a>
                <a class="circle" href="#"></a>
            </nav>
        </div>
        <div class="exclusive_product clearfix">
            <div class="img_left">
                <div class="block_text_exclusive pr_c">
                    <h3>эксклюзив</h3>
                    <h2>Светильник</h2>
                    <p>Уникальная форма. Новинка на рынке.</p>
                    <a class="button_order" href="#">Заказать<img src="{% static '/img/arrow.png' %}" alt=""></a>
                </div>
            </div>
            <div class="products">
                <a href=""><img src="{% static '/img/product_heli.jpg' %}" alt=""></a>
                <div></div>
                <a href=""><img src="{% static '/img/product_house.jpg' %}" alt=""></a>
                <a href=""><img src="{% static '/img/product_owl.jpg' %}" alt=""></a>
                <div></div>
                <a href=""><img src="{% static '/img/product_truck.jpg' %}" alt=""></a>
            </div>
        </div>
        <!-- <div class="back">
            <div class="back_text">
                <h3>mobile app</h3>
                <h2>find. follow. favorite.</h2>
                <p>Save your favorites and share your style.</p>
                <a href=""><img src="{% static '/img/app-store.jpg" alt=""></a>
                <a href=""><img src="{% static '/img/google-play.jpg" alt=""></a>
            </div>
        </div>-->
    </div> <!-- ====== CONTENT END ====== -->
{% endblock %}

mainapp/templates/mainapp/product_detail.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
{{ block.super }} - {{ title }}
{% endblock%}

{% block container %}
<!-- ====== CONTAINER ====== -->
<div class="container clearfix">
    <!--<div class="hero-back">-->
    {% include 'mainapp/includes/inc__main_menu.html' %}
    <!--<div class="h2">Каталог товаров</div>-->
    <!--</div>-->

    <!-- ====== CONTENT ====== -->
    <div class="content">
        {% include 'mainapp/includes/inc__menu_content.html' %}
        <div class="product">
            {% include 'mainapp/includes/inc__product_detail.html' %}
        </div>

        <div class="product_header">
            <h2>Похожие товары</h2>
            <a class="explore" href="{% url 'products:category' hot_product.category.pk %}">показать все
                <img src="{% static '/img/arrow.png' %}" alt="">
            </a>
        </div>
        <div class="pic">
            {% for product in same_products %}
                <a href="{% url 'products:product' product.pk %}"><img src="/media/{{ product.image }}" alt=""></a>
            <!--<a href="#"><img src="img/product-21.jpg" alt=""></a>-->
            <!--<a href="#"><img src="img/product-31.jpg" alt=""></a>-->
            {% endfor %}
        </div>
    </div>    <!-- ====== CONTENT END ====== -->
</div>     <!-- ====== CONTAINER END ====== -->
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load tags %}

{% block title %}
{{ block.super }} - {{ title }}
{% endblock%}

{% block container %}
<!-- ====== CONTAINER ====== -->
<div class="container clearfix">
    <!--<div class="hero-back">-->
        {% include 'mainapp/includes/inc__main_menu.html' %}
        <!--<div class="h2">Каталог товаров</div>-->
    <!--</div>-->

    <!-- ====== CONTENT ====== -->
    <div class="content">
        {% include 'mainapp/includes/inc__menu_content.html' %}
        {% if products %}
            <div class="product_header">
                <div>
                    {% if request.resolver_match.args.0 == '0' %}
                    <h2>Каталог</h2>
                    {% else %}
                    <h2>{{ products.0.category.name }}</h2>
                    {% endif %}
                </div>
                <div>
                    {% if products.has_previous %}
                    <a href="{% url 'products:page' category_pk products.previous_page_number %}">
                        <button class="btn-cat"><<</button>
                    </a>
                    {% endif %}
                    <button class="btn-cat">{{ products.number }}</button> - <button class="btn-cat">{{ products.paginator.num_pages }}</button>
                    {% if products.has_next %}
                        <a href="{% url 'products:page' category_pk products.next_page_number %}">
                            <button class="btn-cat">>></button>
                        </a>
                    {% endif %}
                </div>
                <!--<a class="explore" href="#">показать все<img src="{% static '/img/arrow.png' %}" alt=""></a>-->
            </div>
            <div class="pic prod">
                {% for product in products %}
                    <a href="{% url 'products:product' product.pk %}">
                        <img src="{{ product.image|default_image }}" alt="">
                    </a>
                {% endfor %}
            </div>
        {% endif %}
    </div>    <!-- ====== CONTENT END ====== -->
</div>     <!-- ====== CONTAINER END ====== -->
{% endblock %}